### ISSUE TITLE
URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'

### ISSUE THREAD

**Issue by hejiafeng** [lmxdawn/vue-admin-html-java#5]
npm run sever
然后浏览器输入http://localhost:8080/
提示URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'，请问怎么处理？

URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'
    at decodeURIComponent (<anonymous>)
    at decode_param (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\layer.js:172:12)
    at Layer.match (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\layer.js:123:27)
    at matchLayer (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:574:18)
    at next (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:220:15)
    at expressInit (D:\javaweb\vue-admin-html-java\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:317:13)
    at D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:335:12)
    at next (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:275:10)
    at query (D:\javaweb\vue-admin-html-java\node_modules\express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:317:13)
    at D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:335:12)

**Comment by lmxdawn** [comment]
npm run serve
执行这个哦
这样才算运行成功了哦





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hejiafeng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月19日(星期三) 下午5:48
收件人:&nbsp;"lmxdawn/vue-admin-html-java"<vue-admin-html-java@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[lmxdawn/vue-admin-html-java] URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico' (#5)




npm run sever
 然后浏览器输入http://localhost:8080/
 提示URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'，请问怎么处理？
 
URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'
 at decodeURIComponent ()
 at decode_param (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\layer.js:172:12)
 at Layer.match (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\layer.js:123:27)
 at matchLayer (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:574:18)
 at next (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:220:15)
 at expressInit (D:\javaweb\vue-admin-html-java\node_modules\express\lib\middleware\init.js:40:5)
 at Layer.handle [as handle_request] (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\layer.js:95:5)
 at trim_prefix (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:317:13)
 at D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:284:7
 at Function.process_params (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:335:12)
 at next (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:275:10)
 at query (D:\javaweb\vue-admin-html-java\node_modules\express\lib\middleware\query.js:45:5)
 at Layer.handle [as handle_request] (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\layer.js:95:5)
 at trim_prefix (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:317:13)
 at D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:284:7
 at Function.process_params (D:\javaweb\vue-admin-html-java\node_modules\express\lib\router\index.js:335:12)

**Comment by hejiafeng** [comment]
可以了
